# Generated by Django 5.1.4 on 2024-12-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_students_date_students_email_students_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="date",
        ),
    ]
